#!/usr/bin/env python3
"""Maintain the schema.org block in each standalone application page.

The applications already carry hand-written crawler metadata in their <head> —
a description, a canonical link, Open Graph. What they had no way to say is
*what kind of thing they are*: a search engine reading circuit.html sees a
title, a sentence of description and an empty body, because the whole app is
an iframe that only exists once JavaScript has run. A WebApplication node tells
it there is a free, browser-based circuit simulator at that URL without having
to render anything.

Everything in the block is derived from what the page and the menu already
declare — the name and grouping come from content/applications/menu.json, the
description and URL from the page's own meta tags — so there is no second list
of application descriptions to keep in step with the first. Adding a sentence
to a page's <meta name="description"> and re-running this script is the whole
workflow for changing what a crawler is told about an app.

Pages that opt out of indexing (robots: noindex — the theme editor, the file
manager, the games, everything that is desktop furniture rather than a tool
someone might search for) get any existing block removed instead: the sitemap
already leaves them out and structured data describing an unindexed page is
just noise.

Re-run after editing an application's description, its menu entry, or after
adding a new application:

    python3 scripts/build_app_metadata.py

Use --check to verify without writing, which is what CI does.
"""

import json
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
content = root / 'content'
apps = content / 'applications'

site = json.loads((content / 'site.json').read_text(encoding='utf-8'))
SITE_URL = site.get('siteUrl', 'https://clacktronics.co.uk/')
SITE_NAME = 'Clacktronics'
SAME_AS = [u for u in site.get('sameAs', []) if isinstance(u, str) and u.strip()]

# The block is rewritten in place on every run, so it is fenced by a comment we
# can find again. Anything between the marker and the end of the script tag
# belongs to this generator.
MARKER = ('<!-- schema.org metadata — generated by scripts/build_app_metadata.py; '
          'edit the description above instead -->')
# The leading indentation is part of what gets removed: leaving it behind would
# push the following line further right on every run.
BLOCK_RE = re.compile(
    r'^[ \t]*' + re.escape(MARKER)
    + r'\n[ \t]*<script type="application/ld\+json">.*?</script>\n',
    re.S | re.M)

# schema.org's applicationCategory is a controlled-ish vocabulary and the menu
# already groups the apps the way a person would. Mapping one to the other
# keeps the grouping in a single place: move an app between submenus and its
# category follows.
CATEGORIES = {
    'Games': 'GameApplication',
    'Emulation': 'DeveloperApplication',
    'Multimedia': 'MultimediaApplication',
    'Maths & Programming': 'DeveloperApplication',
    'Electronics': 'DesignApplication',
    'Internet': 'UtilitiesApplication',
    'System': 'UtilitiesApplication',
}
DEFAULT_CATEGORY = 'UtilitiesApplication'


def menu_index():
    """Map each application page to its (label, submenu label).

    Walks the Applications menu recursively so a page nested two submenus deep
    is still found, and remembers the nearest enclosing submenu as the grouping.
    """
    index = {}

    def walk(items, group):
        for item in items:
            if item.get('type') == 'submenu':
                walk(item.get('items', []), item.get('label', group))
            elif item.get('type') == 'app' and item.get('page'):
                index[item['page']] = (item.get('label') or item.get('title', ''),
                                       group)

    menu = json.loads((apps / 'menu.json').read_text(encoding='utf-8'))
    walk(menu.get('items', []), '')
    return index


def meta_content(head, pattern):
    """The content="…" of the first meta/link matching pattern, unescaped."""
    m = re.search(pattern, head, re.I)
    if not m:
        return ''
    # The values were written as HTML attributes, so they carry entities that
    # have to come back out before being re-encoded as JSON.
    text = m.group(1)
    for entity, char in (('&quot;', '"'), ('&#x27;', "'"), ('&#39;', "'"),
                         ('&lt;', '<'), ('&gt;', '>'), ('&amp;', '&')):
        text = text.replace(entity, char)
    return text.strip()


def publisher():
    """The Organization node, sharing the @id the plain mirror's home page uses.

    Both files pointing at the same @id is what lets a search engine read the
    apps and the site as one publisher rather than as two organisations that
    happen to have the same name.
    """
    data = {'@type': 'Organization', '@id': SITE_URL + '#organization',
            'name': SITE_NAME, 'url': SITE_URL}
    if SAME_AS:
        data['sameAs'] = SAME_AS
    return data


def build_block(name, url, description, group, indent):
    """The <script type="application/ld+json"> block for one application."""
    data = {
        '@context': 'https://schema.org',
        '@type': 'WebApplication',
        'name': name,
        'url': url,
        'applicationCategory': CATEGORIES.get(group, DEFAULT_CATEGORY),
        'operatingSystem': 'Any',
        'browserRequirements': 'Requires JavaScript.',
        'inLanguage': 'en-GB',
        # Every app runs client-side and costs nothing; saying so explicitly is
        # what distinguishes these from the trial downloads a search engine
        # otherwise assumes a "WebApplication" to be.
        'isAccessibleForFree': True,
        'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'GBP'},
        'publisher': publisher(),
    }
    if description:
        data['description'] = description
    if group:
        data['applicationSubCategory'] = group
    body = json.dumps(data, ensure_ascii=False).replace('</', r'<\/')
    return (f'{indent}{MARKER}\n'
            f'{indent}<script type="application/ld+json">{body}</script>\n')


def strip_suffix(title):
    """'Resistor Calculator — ClackOS' -> 'Resistor Calculator'."""
    return re.sub(r'\s*[—-]\s*ClackOS\s*$', '', title).strip()


def process(path, index, write):
    """Refresh (or remove) one application's block. Returns True if it changed."""
    original = path.read_text(encoding='utf-8')
    source = BLOCK_RE.sub('', original)

    head = source[:6000]
    rel = path.relative_to(apps).as_posix()
    canonical = meta_content(head, r'<link\s+rel="canonical"\s+href="([^"]*)"')
    noindex = re.search(r'<meta\s+name="robots"[^>]*noindex', head, re.I)

    # Desktop furniture and anything not yet described for crawlers keeps no
    # block at all — the same two tests build_plain_site.py uses to decide what
    # belongs in the sitemap, so the two files cannot disagree about an app.
    if noindex or not canonical:
        updated = source
    else:
        label, group = index.get(rel, ('', ''))
        title = meta_content(head, r'<title>([^<]*)</title>')
        name = label or strip_suffix(title)
        description = meta_content(
            head, r'<meta\s+name="description"\s+content="([^"]*)"')

        # The block goes directly after the last crawler tag in the head, which
        # keeps it inside the first few kB that build_plain_site.py reads when
        # it looks for the canonical link.
        anchor = re.search(
            r'^([ \t]*)<meta\s+name="twitter:card"[^>]*>\n', source,
            re.I | re.M)
        if not anchor:
            anchor = re.search(
                r'^([ \t]*)<link\s+rel="canonical"[^>]*>\n', source, re.I | re.M)
        if not anchor:
            print(f'  ! {rel}: no place to put the block', file=sys.stderr)
            return False
        indent = anchor.group(1)
        block = build_block(name, canonical, description, group, indent)
        updated = source[:anchor.end()] + block + source[anchor.end():]

        if rel not in index:
            print(f'  ! {rel}: not in menu.json, category guessed', file=sys.stderr)

    if updated == original:
        return False
    if write:
        path.write_text(updated, encoding='utf-8', newline='\n')
    return True


def main():
    write = '--check' not in sys.argv
    index = menu_index()
    changed = [p.relative_to(apps).as_posix()
               for p in sorted(apps.rglob('*.html'))
               if process(p, index, write)]

    if not write and changed:
        print('Application metadata is out of date:', file=sys.stderr)
        for rel in changed:
            print(f'  {rel}', file=sys.stderr)
        print('Run: python3 scripts/build_app_metadata.py', file=sys.stderr)
        return 1
    print(f'{"Would update" if not write else "Updated"} {len(changed)} '
          f'application page(s).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
