#!/usr/bin/env python3
"""Generate the fixed mapper noise Magenta RealTime 2 needs.

MusicCoCa's mapper — the step that carries a text embedding into the audio
style space its quantizer was trained on — takes a gaussian noise vector as a
second input. The reference implementation uses one fixed draw, seed 0, and
using any other noise gives different style tokens and so a different piece of
music for the same prompt. It is 768 floats; this writes them into
content/applications/audiogen/mrt2/mapper-noise.js as base64, rather than
having the app carry an opaque blob with no way to check where it came from.

Re-run only if that file is lost — the output is deterministic, and changing it
would silently change what every prompt sounds like:

    python3 scripts/build_mrt2_noise.py
    python3 scripts/build_mrt2_noise.py --check
"""

import argparse
import base64
import pathlib
import sys

import numpy as np

TARGET = pathlib.Path("content/applications/audiogen/mrt2/mapper-noise.js")

HEADER = """/* GENERATED by scripts/build_mrt2_noise.py — do not edit.
 *
 * MusicCoCa's mapper takes a text embedding and a fixed gaussian noise vector.
 * This is that vector: numpy's RandomState(0).randn(768), little-endian
 * float32, base64. The seed is not arbitrary — it is the one the reference
 * implementation uses, and it is what makes a prompt produce the same style
 * tokens here as it does there.
 */
"""

BODY = """
const NOISE = '{noise}';

export const MAPPER_NOISE = (() => {{
  const binary = atob(NOISE);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return new Float32Array(bytes.buffer);
}})();
"""


def render() -> str:
    noise = np.random.RandomState(0).randn(768).astype("<f4").tobytes()
    return HEADER + BODY.format(noise=base64.b64encode(noise).decode("ascii"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    arguments = parser.parse_args()

    wanted = render()
    if arguments.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current == wanted:
            print(f"{TARGET} is up to date.")
            return 0
        print(f"{TARGET} does not match seed 0.", file=sys.stderr)
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(wanted, encoding="utf-8")
    print(f"Wrote {TARGET} (768 floats).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
