#!/usr/bin/env python3
"""Point dead outbound links at the Wayback Machine instead.

Walks the markdown in content/, checks every external link, and for the ones
that are genuinely gone rewrites the URL to an archive.org snapshot and marks
it in the text:

    [Vintage Synth Explorer](http://www.vintagesynth.com/misc/octavecat.php)

becomes

    [Vintage Synth Explorer](https://web.archive.org/web/20110125.../misc/octavecat.php) (wayback mirror)

Which snapshot it picks depends on the file. A blog post is named
YYYY-MM-DD-slug.md, so its links get the snapshot closest to the day the post
was written — that is the page the post was actually talking about. Anything
else (the static windows, the project pages) gets the newest snapshot.

Being wrong here means silently replacing a working link, so the checker only
treats a link as dead on an unambiguous answer: 404, 410, or a hostname/host
that does not resolve or refuses the connection. A 403, a 429, a 500 or a
timeout means "cannot tell" and the link is left exactly as it is. Re-running
is safe: links already pointing at web.archive.org are skipped, and so is any
link already carrying the marker.

Usage:
    python3 scripts/wayback_dead_links.py --dry-run     # report, change nothing
    python3 scripts/wayback_dead_links.py               # rewrite in place
    python3 scripts/wayback_dead_links.py --report out.md

Stdlib only, so it runs on a bare runner with no pip install.
"""
import argparse
import concurrent.futures
import datetime
import json
import pathlib
import re
import socket
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / 'content'

MIRROR_LABEL = ' (wayback mirror)'

UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/124.0 Safari/537.36 clacktronics-link-check/1.0')

# Hosts never checked. archive.org because that is where we are sending things,
# and localhost/example.com because they are placeholders by definition.
SKIP_HOSTS = {
    'web.archive.org',
    'archive.org',
    'localhost',
    'example.com',
    'www.example.com',
}

# A link is only rewritten when the server gives one of these answers.
DEAD_STATUSES = {404, 410}

# `[text](url)` and `![alt](url)`, with the leading `!` captured so images can
# be told apart from links. The URL part allows one level of nested parens so
# that Wikipedia-style /wiki/Foo_(bar) URLs survive, and an optional "title".
LINK_RE = re.compile(
    r'(?P<bang>!?)\['
    r'(?P<text>(?:[^\[\]]|\[[^\[\]]*\])*)'
    r'\]\(\s*'
    r'(?P<url>[^()\s]*(?:\([^()\s]*\)[^()\s]*)*)'
    r'(?P<title>\s+"[^"]*")?'
    r'\s*\)'
)

POST_DATE_RE = re.compile(r'^(\d{4})-(\d{2})-(\d{2})-')

# Generated by build_blog_index.py from the posts in content/file/blog/. They
# are skipped when scanning a directory: rewriting them here would date their
# links from today rather than from the post they came out of, and the next
# index rebuild would overwrite the lot anyway. Fix the posts, rebuild the
# index. Naming one on the command line still scans it.
GENERATED_RE = re.compile(r'^(blog|blog-list|blog-page-\d+)\.md$')


def is_external(url):
    return url.lower().startswith(('http://', 'https://'))


def host_of(url):
    return (urllib.parse.urlsplit(url).hostname or '').lower()


def skipped(url, extra_hosts=()):
    host = host_of(url)
    if not host:
        return True
    hosts = set(SKIP_HOSTS) | set(extra_hosts)
    return any(host == h or host.endswith('.' + h) for h in hosts)


def probe_network(timeout):
    """Is there a working way out to the web at all?

    A run with no network would see every link fail and, without this, could
    decide the entire site is dead. Both schemes are tried because proxies
    sometimes pass one and not the other.
    """
    for url in ('https://example.com/', 'http://example.com/'):
        try:
            with open_url(url, 'GET', timeout) as response:
                if response.status < 400:
                    return True
        except urllib.error.HTTPError:
            return True                # a real server answered; the wire works
        except Exception:
            continue
    return False


def file_timestamp(path):
    """Wayback timestamp (YYYYMMDDhhmmss) to aim for when archiving `path`.

    Blog posts carry their date in the filename, so their links resolve to the
    web as it looked when the post went up. Everything else asks for now, which
    the availability API answers with the most recent snapshot.
    """
    m = POST_DATE_RE.match(path.name)
    if m:
        return f'{m.group(1)}{m.group(2)}{m.group(3)}120000'
    return datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%d%H%M%S')


def rel_path(path):
    """Repo-relative path for reporting, or the path itself if it sits outside."""
    try:
        return path.relative_to(ROOT)
    except ValueError:
        return path


def open_url(url, method, timeout):
    request = urllib.request.Request(url, method=method, headers={
        'User-Agent': UA,
        'Accept': '*/*',
    })
    return urllib.request.urlopen(request, timeout=timeout)


def host_resolves(host, timeout=5):
    """Does `host` have a DNS record right now?

    Used to second-guess a connection error. Behind a proxy — a CI runner, or
    the sandbox this was written in — urllib can report "name or service not
    known" for a host that resolves perfectly well, and taking that at face
    value would archive a pile of links that were never dead.
    """
    old = socket.getdefaulttimeout()
    socket.setdefaulttimeout(timeout)
    try:
        socket.getaddrinfo(host, None)
        return True
    except Exception:
        return False
    finally:
        socket.setdefaulttimeout(old)


def check_url(url, timeout, attempts=2):
    """('dead'|'alive'|'unknown', detail) for one URL.

    HEAD first because it is cheap, then GET — plenty of servers (and most
    CDNs fronting old sites) answer HEAD with 403 or 405 while serving the page
    perfectly well over GET, and a HEAD-only check would call those dead.
    """
    detail = ''
    for attempt in range(attempts):
        for method in ('HEAD', 'GET'):
            try:
                with open_url(url, method, timeout) as response:
                    return 'alive', f'{response.status} {method}'
            except urllib.error.HTTPError as err:
                detail = f'HTTP {err.code}'
                if err.code in DEAD_STATUSES:
                    return 'dead', detail
                if method == 'GET':
                    # 403/429/5xx: the server is there and saying something
                    # other than "gone". Not our call to make.
                    return 'unknown', detail
            except urllib.error.URLError as err:
                reason = err.reason
                detail = f'{type(reason).__name__}: {reason}'
                if isinstance(reason, socket.gaierror):
                    if not host_resolves(host_of(url)):
                        return 'dead', 'host does not resolve'
                    detail = 'DNS error, but the host resolves — inconclusive'
                    return 'unknown', detail
                if isinstance(reason, ConnectionRefusedError):
                    return 'dead', 'connection refused'
                break                      # timeouts, TLS, resets: try again
            except (socket.timeout, TimeoutError):
                detail = 'timeout'
                break
            except Exception as err:       # malformed URL, odd redirect, ...
                return 'unknown', f'{type(err).__name__}: {err}'
        if attempt + 1 < attempts:
            time.sleep(2 * (attempt + 1))
    return 'unknown', detail or 'no answer'


def _api_json(url, timeout, attempts=3):
    """GET some JSON, retrying — archive.org throttles and times out freely.

    Giving up too early would look like "no snapshot exists" and leave a dead
    link in place, so it is worth a couple of waits.
    """
    for attempt in range(attempts):
        try:
            with open_url(url, 'GET', timeout) as response:
                return json.loads(response.read().decode('utf-8', 'replace'))
        except Exception:
            if attempt + 1 == attempts:
                raise
            time.sleep(3 * (attempt + 1))


def wayback_snapshot(url, timestamp, timeout):
    """Best archive.org snapshot of `url` near `timestamp`, or None.

    Tries the availability API first, then falls back to the CDX index, which
    answers for some URLs the availability API shrugs at. Both are asked for
    the closest capture to the post's own date.
    """
    quoted = urllib.parse.quote(url, safe='')
    try:
        data = _api_json(
            f'https://archive.org/wayback/available?url={quoted}&timestamp={timestamp}',
            timeout)
        closest = (data.get('archived_snapshots') or {}).get('closest') or {}
        if closest.get('available') and closest.get('url'):
            # The API hands back http:// URLs; https works and avoids a hop.
            return closest['url'].replace('http://web.archive.org', 'https://web.archive.org', 1)
    except Exception:
        pass

    try:
        rows = _api_json(
            'https://web.archive.org/cdx/search/cdx?url=' + quoted +
            '&output=json&fl=timestamp,original&filter=statuscode:200'
            '&collapse=timestamp:6&limit=200',
            timeout)
    except Exception:
        return None
    if not isinstance(rows, list) or len(rows) < 2:
        return None
    stamps = [row[0] for row in rows[1:] if row and row[0].isdigit()]
    if not stamps:
        return None
    target = int(timestamp)
    best = min(stamps, key=lambda s: abs(int(s) - target))
    return f'https://web.archive.org/web/{best}/{url}'


class Checker:
    """Checks URLs once each, with a cache that survives between runs."""

    def __init__(self, cache_path, ttl_days, timeout):
        self.path = cache_path
        self.ttl = datetime.timedelta(days=ttl_days)
        self.timeout = timeout
        self.lock = threading.Lock()
        self.cache = {}
        if cache_path and cache_path.exists():
            try:
                self.cache = json.loads(cache_path.read_text())
            except Exception:
                self.cache = {}

    def _fresh(self, entry):
        try:
            when = datetime.datetime.fromisoformat(entry['checked'])
        except Exception:
            return False
        return datetime.datetime.now(datetime.timezone.utc) - when < self.ttl

    def status(self, url):
        with self.lock:
            entry = self.cache.get(url)
            if entry and self._fresh(entry):
                return entry['status'], entry.get('detail', 'cached')
        status, detail = check_url(url, self.timeout)
        with self.lock:
            self.cache[url] = {
                'status': status,
                'detail': detail,
                'checked': datetime.datetime.now(datetime.timezone.utc).isoformat(),
            }
        return status, detail

    def save(self):
        if not self.path:
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(self.cache, indent=1, sort_keys=True) + '\n')


def collect(paths, include_images, extra_skip_hosts=()):
    """{url: [path, ...]} for every candidate link in `paths`."""
    found = {}
    for path in paths:
        text = path.read_text(encoding='utf-8')
        for match in LINK_RE.finditer(text):
            url = match.group('url').strip('<>')
            if match.group('bang') and not include_images:
                continue
            if not is_external(url) or skipped(url, extra_skip_hosts):
                continue
            if text[match.end():match.end() + len(MIRROR_LABEL)] == MIRROR_LABEL:
                continue               # already mirrored on an earlier run
            found.setdefault(url, []).append(path)
    return found


def rewrite(path, replacements, include_images):
    """Swap in mirror URLs and add the marker. Returns how many links changed."""
    text = path.read_text(encoding='utf-8')
    out = []
    cursor = 0
    changed = 0
    for match in LINK_RE.finditer(text):
        url = match.group('url').strip('<>')
        mirror = replacements.get(url)
        if not mirror:
            continue
        if match.group('bang') and not include_images:
            continue
        if text[match.end():match.end() + len(MIRROR_LABEL)] == MIRROR_LABEL:
            continue
        out.append(text[cursor:match.start('url')])
        out.append(mirror)
        out.append(text[match.end('url'):match.end()])
        # Images are swapped silently — a marker inside an image would render
        # as stray text next to the picture.
        if not match.group('bang'):
            out.append(MIRROR_LABEL)
        cursor = match.end()
        changed += 1
    if not changed:
        return 0
    out.append(text[cursor:])
    path.write_text(''.join(out), encoding='utf-8')
    return changed


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('paths', nargs='*', type=pathlib.Path,
                        help='files or directories to scan (default: content/)')
    parser.add_argument('--dry-run', action='store_true',
                        help='report what would change without touching files')
    parser.add_argument('--include-images', action='store_true',
                        help='also repoint dead ![image](url) sources')
    parser.add_argument('--site-host', default='clacktronics.co.uk',
                        help='this site\'s own host, left alone by default')
    parser.add_argument('--include-site', action='store_true',
                        help='also check links to --site-host (old permalinks '
                             'from the WordPress days live there and many are '
                             'gone, but so do the assets this site serves, so '
                             'run it with --dry-run first)')
    parser.add_argument('--report', type=pathlib.Path,
                        help='write a markdown summary here')
    parser.add_argument('--cache', type=pathlib.Path,
                        default=ROOT / '.link-check-cache.json',
                        help='where to remember link statuses between runs')
    parser.add_argument('--no-cache', action='store_true')
    parser.add_argument('--cache-days', type=float, default=7.0,
                        help='how long a cached status stays good (default 7)')
    parser.add_argument('--timeout', type=float, default=20.0)
    parser.add_argument('--workers', type=int, default=8,
                        help='parallel link checks (default 8)')
    parser.add_argument('--limit', type=int, default=0,
                        help='stop after rewriting N links (0 = no limit)')
    parser.add_argument('--max-dead-fraction', type=float, default=0.5,
                        help='bail out without rewriting if more than this '
                             'share of links look dead — that is a broken '
                             'network, not a broken web (default 0.5)')
    args = parser.parse_args()

    targets = args.paths or [CONTENT]
    files = []
    for target in targets:
        target = target.resolve()
        if target.is_dir():
            files.extend(sorted(p for p in target.rglob('*.md')
                                if not GENERATED_RE.match(p.name)))
        elif target.suffix == '.md':
            files.append(target)
    if not files:
        print('no markdown found', file=sys.stderr)
        return 1

    if not probe_network(args.timeout):
        print('no route to the web — refusing to judge anything dead',
              file=sys.stderr)
        return 1

    extra_skip = () if args.include_site else (args.site_host.lower(),)
    links = collect(files, args.include_images, extra_skip)
    print(f'{len(files)} files, {len(links)} external links to check')
    if not links:
        print('nothing to check')
        return 0

    checker = Checker(None if args.no_cache else args.cache,
                      args.cache_days, args.timeout)
    dead = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(checker.status, url): url for url in links}
        for future in concurrent.futures.as_completed(futures):
            url = futures[future]
            status, detail = future.result()
            if status == 'dead':
                dead.append((url, detail))
    checker.save()

    dead.sort()
    print(f'{len(dead)} dead')
    if len(dead) > args.max_dead_fraction * len(links):
        print(f'{len(dead)} of {len(links)} links look dead — that is more '
              'likely a network problem here than a dead web. Nothing was '
              'changed; re-run with a higher --max-dead-fraction to override.',
              file=sys.stderr)
        return 1

    # Snapshot lookups are serialised on purpose: archive.org throttles hard,
    # and a 429 here would look like "no mirror exists" and skip a good link.
    mirrors = {}      # url -> mirror URL, per target date
    no_mirror = []
    rewritten = 0
    report = ['# Dead link sweep',
              '',
              f'_{datetime.datetime.now(datetime.timezone.utc):%Y-%m-%d %H:%M UTC}_',
              '',
              f'- files scanned: {len(files)}',
              f'- external links: {len(links)}',
              f'- dead: {len(dead)}',
              '']

    per_file = {}
    for url, detail in dead:
        for path in links[url]:
            per_file.setdefault(path, []).append((url, detail))

    for path in sorted(per_file):
        timestamp = file_timestamp(path)
        replacements = {}
        for url, detail in per_file[path]:
            if args.limit and rewritten >= args.limit:
                break
            key = (url, timestamp)
            if key not in mirrors:
                mirrors[key] = wayback_snapshot(url, timestamp, args.timeout)
                time.sleep(1)
            mirror = mirrors[key]
            rel = rel_path(path)
            if not mirror:
                no_mirror.append((rel, url, detail))
                continue
            replacements[url] = mirror
            report.append(f'- `{rel}` — {detail}')
            report.append(f'  - was: {url}')
            report.append(f'  - now: {mirror}')
            rewritten += 1
        if replacements and not args.dry_run:
            rewrite(path, replacements, args.include_images)

    if no_mirror:
        report += ['', '## Dead, but no snapshot on archive.org', '']
        report += [f'- `{rel}` — {url} ({detail})' for rel, url, detail in no_mirror]

    text = '\n'.join(report) + '\n'
    if args.report:
        args.report.write_text(text, encoding='utf-8')
    print(text)
    verb = 'would rewrite' if args.dry_run else 'rewrote'
    print(f'{verb} {rewritten} link(s); {len(no_mirror)} dead with no mirror')
    return 0


if __name__ == '__main__':
    sys.exit(main())
